version: "3"

services:
  fleetman-webapp:
    image: lucasgabrielsa/fleetman-web-app-maven
    networks:
      - fleetman-network
    ports:
      - 81:8080
    depends_on:
      - database

  database:
    image: mysql:5
    networks:
      - fleetman-network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=fleetman

networks:
  fleetman-network:

